name: XModAlg
version: 1.16
date: 2018-01-29
description: |
    Crossed Modules and Cat1-Algebras

authors:
    - name: Zekeriya Arvasi
      url: mailto:zarvasi@ogu.edu.tr
    - name: Alper Odabas
      url: mailto:aodabas@ogu.edu.tr

maintainers:
    - name: Alper Odabas
      url: mailto:aodabas@ogu.edu.tr

GAP: ">=4.8.8"

needed-pkgs:
    - name: "XMod"
      version: ">=2.64"
      url: "https://gap-packages.github.io/xmod/"
    - name: "LAGUNA"
      version: ">=3.7.0"
      url: "https://gap-packages.github.io/laguna"

suggested-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/xmodalg/
readme: README.md
packageinfo: https://gap-packages.github.io/xmodalg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/xmodalg/releases/download/v1.16/XModAlg-1.16.tar.gz

abstract: |
    The <span class="pkgname">XModAlg</span> package provides a collection of functions for computing with crossed modules and cat1-algebras and morphisms of these structures.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
